### PR TITLE
A plugin to subscribe proposal

### PR DESCRIPTION
**Pull request by Dapiguabc**
The detail can be found on https://github.com/Dapiguabc/snapshot-subscribe

### CODE REVIEW

**Comment by bonustrack** [comment]
@Dapiguabc Hey we've moved the plugins to another repository last week could you do that PR on this repo instead: https://github.com/snapshot-labs/snapshot-plugins

**Comment by Dapiguabc** [comment]
Ok, I will do it tomorrow
> @Dapiguabc Hey we've moved the plugins to another repository last week could you do that PR on this repo instead: https://github.com/snapshot-labs/snapshot-plugins Also run the lint script

**Comment by Dapiguabc** [comment]
@bonustrack I have make a new PR on this repo instead: https://github.com/snapshot-labs/snapshot-plugins.

**Comment by bonustrack** [comment]
Closing this PR for now.

**Pull request closed without merging**
