### PR TITLE
Add Fuse network support

### LINKED ISSUE #228: Add Fuse network support
### Expected behavior
Being able to use Fuse in the supported networks
### Actual behavior
Fuse is not a supported network yet
### Steps to reproduce the behavior
Browse https://snapshot.page/#/networks

### PR DESCRIPTION
**Pull request by bertux**
Fixes #228 .

Changes proposed in this pull request:
- Add Fuse network logo
- Add Fuse network RPC details
- Add Fuse network contract address

### CODE REVIEW

**Comment by bonustrack** [comment]
@bertux Hi sorry for late review. Is the node an archive node? Also can you add a multicall contract here: https://github.com/maswalker/snapshot.js/blob/master/src/utils.ts#L21

**Comment by bertux** [comment]
> @bertux Hi sorry for late review. Is the node an archive node? Also can you add a multicall contract here: https://github.com/snapshot-labs/snapshot.js/blob/master/src/utils.ts#L21

Hello, sorry for late reply, I've verified with Fuse team the node is an archive node and it's already used as archive node for TheGraph indexing.
I will add the multicall contract in my next commit.

**Comment by bonustrack** [comment]
@bertux Sound good!

**Comment by bertux** [comment]
@bonustrack I've deployed on Fuse the Mutlicall contract and published the source code on the block explorer.
I've added the deployment address where all the Mutlicall deployments addresses are now.
I hope you will be able to merge it this month. Let me know if I've forgotten anything.

**Review by bonustrack — APPROVED** [review]
Looks good!

**Pull request merged**
