### PR TITLE
AVN strategy for AVT staking holders

### PR DESCRIPTION
**Pull request by andrew-frank**
Changes proposed in this pull request:
- add strategy for AVN voting strategy

### CODE REVIEW

**Comment by bonustrack** [comment]
@andrew-frank Hey is your PR ready?

**Comment by bonustrack** [comment]
Looks good! Can you just fix the conflict or authorize maintainers to edit your PR so we can do it for you?
image

**Comment by andrew-frank** [comment]
@bonustrack yup, resolved the conflict

**Review by ChaituVR — COMMENTED** [review]
LGTM @bonustrack

**Comment by andrew-frank** [comment]
Hello, re-resolved conflicts again. Can you please merge this PR @bonustrack  ?

**Comment by bonustrack** [comment]
@andrew-frank Sorry i just realize that your strategy will not scale well, strategies are resolved on user browser and i can see there is 2 requests being sent for each voter, if there is 1000 voters there will be 2000 requests sent, it's way too much for a browser to handle, can you find another way to handle the strategy to get max 5-6 requests?

**Comment by andrew-frank** [comment]
@bonustrack thanks for looking into it. I thought the votes calculations is executed for (my) short list of addresses, not for everyone involved in voting. Anyway, fixed and got it down to 2 multicall requests. Let me know if all good!

**Review by bonustrack — APPROVED** [review]
Looks good now thanks!

**Pull request merged**
