### PR TITLE
ad HPB network request

### PR DESCRIPTION
**Pull request by loglos**
Fixes # .

Changes proposed in this pull request:
- add hpbdao.eth  network  request
- 
-

### CODE REVIEW

**Comment by bonustrack** [comment]
@loglos Is the RPC node an archive node? Also you will need to add a multicall contract, see here for more info: https://docs.snapshot.org/networks#add-a-new-network

**Comment by loglos** [comment]
https://hpb.app It is the synchronization node of HPB main network and the normal operator.

**Comment by bonustrack** [comment]
@loglos Does it mean it's an archive node? Also can you add a multicall address?

**Comment by bonustrack** [comment]
Closing this PR for now, feel free to open it again once you've done the changes.

**Pull request closed without merging**
