### PR TITLE
[celer-sgn-delegation] Add Celer SGN delegation strategy

### PR DESCRIPTION
**Pull request by Dominator008**
Counts the delegated stakes to all validators for each address.

### CODE REVIEW

**Comment by modong** [comment]
@ChaituVR to provide a bit more context. This is for protocol governance voting for Celer related protocol changes. Around 30% of all tokens are now staked in Celer's State Guardian Network to provide various liveness and security services for all the layer2 infrastructure and applications built on top of Celer. When voting for protocol improvement proposals, we would like to allow users who have delegated their token in the staking contract to also be able to vote. We would appreciate the Snapshot team merging this as this is a heavily requested feature by our community. Thank you!

**Review by bonustrack — APPROVED** [review]
Looks good!

**Comment by bonustrack** [comment]
Can you just fix the conflicts or give maintainers of the repo ability to edit the branch for you?

**Comment by Dominator008** [comment]
> Can you just fix the conflicts or give maintainers of the repo ability to edit the branch for you?

Done.

**Comment by Dominator008** [comment]
Thanks for the quick review!

**Pull request merged**
