### PR TITLE
[masterchef-pool-balance-price] Add support for single token pools

### PR DESCRIPTION
**Pull request by joaomajesus**
Changes proposed in this pull request:
- add support for single token pools
- no breaking changes

### CODE REVIEW

**Review by ChaituVR — COMMENTED** [review]
LGTM

**Comment by joaomajesus** [comment]
> LGTM

sorry, LGTM?

**Comment by joaomajesus** [comment]
One of our members is saying that he cannot vote on the demo snapshot with the current version of this strategy when using an iPhone with Metamask.
Would you guys have any insight into what my be causing this?

**Comment by bonustrack** [comment]
@joaomajesus Hey, does the user have an error message or something?

**Comment by joaomajesus** [comment]
he was able to select the option he wanted to vote. but when pressing the vote button it flashed but nothing else happened.

**Comment by joaomajesus** [comment]
He uses metamask only

**Comment by bonustrack** [comment]
@joaomajesus Does it work if the user vote here: https://demo.snapshot.org/#/fabien.eth/proposal/Qmd6o2bFhuN2pkXa3qTW32zAcKHwhvz5pcj5rs1NzPcJcx
If yes, then the issue come most likely from the strategy.

**Comment by joaomajesus** [comment]
@bonustrack sorry to have bothered you, our member tested it again and it worked. maybe it was some rpc issue with metamask or some other exotic problem. :)

**Comment by joaomajesus** [comment]
@bonustrack Could you review and approve when you can please? 
Currently the PR is pending on your review.
Thanks.

**Review by bonustrack — APPROVED** [review]

**Pull request merged**
