### PR TITLE
New network support: Energy Web Chain (246)

### PR DESCRIPTION
**Pull request by TopSootPrime**
- new network added: [Energy Web Chain (246)](https://www.energyweb.org/technology/energy-web-chain/), an EVM chain already running for 2 years
- multicall contract added ([verified in explorer](https://explorer.energyweb.org/address/0x0767F26d0D568aB61A98b279C0b28a4164A6f05e/contracts))
- node is archive

Fixes # .

Changes proposed in this pull request:
- 
- 
-

### CODE REVIEW

**Comment by bonustrack** [comment]
Hi! Can you also add an image of the network here: https://github.com/snapshot-labs/snapshot.js/tree/master/src/networks ?
Thank you!

**Comment by TopSootPrime** [comment]
@bonustrack added!

**Review by bonustrack — APPROVED** [review]
Looks good!

**Comment by ChaituVR** [comment]
Hi @TopSootPrime The RPC you've provided is not working, can you provide a new one?

**Pull request merged**
