### PR TITLE
Decentralized Subgraph

### LINKED ISSUE #539: Move to decentralized subgraph

### PR DESCRIPTION
**Pull request by ChaituVR**
Fixes #539 
Fixes https://github.com/snapshot-labs/snapshot-hub/issues/280

### CODE REVIEW

**Comment by mktcode** [comment]
Are we moving to decentralized subgraph?

**Comment by ChaituVR** [comment]
> Are we moving to a decentralized subgraph?

Yep 🚀 🚀 🚀

**Comment by ChaituVR** [comment]
Running a few small tests, once it is done, we can release this new version :)

**Comment by ChaituVR** [comment]
Blocked: Need correct API Key

**Pull request merged**
