### PR TITLE
Feature - Wallet Follow and Unfollow

### PR DESCRIPTION
**Pull request by midgerate**
As seen at the Snapshot hackathon, this PR adds the wallet follow and unfollow methods to snapshot.

### CODE REVIEW

**Comment by midgerate** [comment]
@samuveth I think this PR does not block the one on the hub. Without this the hub cannot merge anyway due to dependency issue.

**Comment by midgerate** [comment]
@samuveth I think this PR does not block the one on the hub. Without this the hub cannot merge anyway due to dependency issue.

**Comment by samuveth** [comment]
@midgerate I think fabien and chaitu should review this one. I see there are some things that might change on the hub PR

**Comment by ChaituVR** [comment]
Looks good to me, will merge once everything is ready on [hub](https://github.com/snapshot-labs/snapshot-hub/pull/277), let me know if we need a beta version for snapshot.js to test on snapshot-hub

**Comment by bonustrack** [comment]
Closing this for now as it's not a feature we would implement anytime soon

**Pull request closed without merging**
