### PR TITLE
Add balance-with-min strategy

### PR DESCRIPTION
**Pull request by samuveth**
Changes proposed in this pull request:
- If balance is below minimum the voting power is replaces with zero
-

### CODE REVIEW

**Review by bonustrack — APPROVED** [review]
Works well!

**Comment by samuveth** [comment]
@bonustrack How long does it usually take until it's live after merge.

**Comment by samuveth** [comment]
Could the this strategy also notify the voter if the balance is below minimum?

**Comment by bonustrack** [comment]
@samuveth When there is a new strategy, the frontend need to be redeployed, i'm doing this now it should be live in 5mn. When user will vote and have less than the minimum he will see 0 as voting power, so somehow he will get notified.

**Comment by sinasabet81** [comment]
Does this affect both voting and proposing? Would it be possible to support a similar strategy that only blocks proposing for users below the threshold?

**Pull request merged**
