### PR TITLE
Add chart plugin

### PR DESCRIPTION
**Pull request by Zerquix18**
My submission for the [snapshot plugin bounty](https://gitcoin.co/issue/snapshot-labs/snapshot/577/100026411). There's a Youtube video to demo this plugin: https://youtu.be/Ax_68hQMs6U

I'm also submitting another pull request to the other repository with the UI.

### CODE REVIEW

**Comment by bonustrack** [comment]
@Zerquix18 Can you remove change on package-lock.json?

**Comment by Zerquix18** [comment]
Hi @bonustrack . Should be solved now.

**Comment by bonustrack** [comment]
@Zerquix18 I still see change on package-lock.json, also can you add an image for the plugin like this https://github.com/snapshot-labs/snapshot.js/blob/master/src/plugins/aragon/logo.png

**Comment by Zerquix18** [comment]
Added a logo & placed the current `package-lock.json` from master.

**Pull request merged**
