### PR TITLE
[infinityprotocol-liquidity-pools] Add Infinity Protocol Strategy

### PR DESCRIPTION
**Pull request by InfinityWallet**
Changes proposed in this pull request:

- We have added the Infinity Protocol Liquidity Pool Strategy

### CODE REVIEW

**Comment by ChaituVR** [comment]
@InfinityWallet Hi please add `infinityprotocol-liquidity-pools-bsc` to https://github.com/snapshot-labs/snapshot.js/blob/master/src/strategies/index.ts

**Comment by InfinityWallet** [comment]
> @InfinityWallet Hi please add `infinityprotocol-liquidity-pools-bsc` to https://github.com/snapshot-labs/snapshot.js/blob/master/src/strategies/index.ts

We have added it into the index.ts

**Comment by InfinityWallet** [comment]
> @InfinityWallet Hi please add `infinityprotocol-liquidity-pools-bsc` to https://github.com/snapshot-labs/snapshot.js/blob/master/src/strategies/index.ts

Any idea when the pull request will get approved? Thanks

**Review by ChaituVR — CHANGES_REQUESTED** [review]

**Comment by ChaituVR** [comment]
@InfinityWallet make sure examples.json include at least 1 address with a positive score(right now it return only empty array, make sure it passes all tests, Thanks

**Comment by InfinityWallet** [comment]
> @InfinityWallet make sure examples.json include at least 1 address with a positive score(right now it return only empty array, make sure it passes all tests, Thanks

It has been changed, however the address that was previously there was fine also.

**Comment by ChaituVR** [comment]
@InfinityWallet when I run this strategy, the output I get is: ` [ {} ]`  not sure what's going wrong.. not there is some other error.. plz check `Test Strategy` github check in this PR.
and make sure you are able to run `npm test --strategy=infinityprotocol-liquidity-pools-bsc` in your local, without any errors, Thanks :)

**Comment by InfinityWallet** [comment]
> @InfinityWallet when I run this strategy, the output I get is: ` [ {} ]` not sure what's going wrong.. not there is some other error.. plz check `Test Strategy` github check in this PR.
> and make sure you are able to run `npm test --strategy=infinityprotocol-liquidity-pools-bsc` in your local, without any errors, Thanks :)

We have updated it, however it fails on the last test due to the primary node you are using. We tried locally by removing https://bsc.getblock.io/mainnet/?api_key=91f8195f-bf46-488f-846a-73d6853790e7 and instead using https://bsc-dataseed1.binance.org which worked fine.

**Comment by ChaituVR** [comment]
@InfinityWallet issue with the node is resolved now.. and looks to be working well..  but can you remove `yarn.lock` file .. thanks

**Comment by InfinityWallet** [comment]
> @InfinityWallet issue with the node is resolved now.. and looks to be working well.. but can you remove `yarn.lock` file .. thanks

We have removed the yarn.lock file, let us know if there is anything else. Thanks

**Comment by ChaituVR** [comment]
LGTM @bonustrack

**Review by bonustrack — APPROVED** [review]
Looking good! The strategy will be live in few min

**Pull request merged**
