### PR TITLE
Fix delegation strategy

### PR DESCRIPTION
**Pull request by ncitron**
The delegation strategy always returns a score of 0 if any of the internal strategies return `{}` (which is a common return value of strategies such as the uniswap strategy). This causes the delegation strategy to often lose a delegatee's voting power.

### CODE REVIEW

**Comment by bonustrack** [comment]
Hi! Thank you for your PR 🙏 . Do you have a proposal where you've noticed this issue?

**Comment by ncitron** [comment]
I discovered this bug while testing out some new strategies for our space using the `test/scores.ts` file. This is my modified version of that file:
```ts
global['fetch'] = require('cross-fetch');
const { JsonRpcProvider } = require('@ethersproject/providers');
const snapshot = require('../');
const networks = require('../src/networks.json');

const space = 'index';
const network = '1';
const strategies = [
  {
    "name": "delegation",
    "params": {
      "symbol": "INDEX (delegated)",
      "strategies": [
        {
          "name": "erc20-balance-of",
          "params": {
            "address": "0x0954906da0Bf32d5479e25f46056d22f08464cab",
            "symbol": "INDEX",
            "decimals": 18
          }
        },
        {
          "name": "sushiswap",
          "params": {
            "address": "0x0954906da0Bf32d5479e25f46056d22f08464cab",
            "symbol": "INDEX (Sushiswap)",
            "decimals": 18
          }
        }
      ]
    }
  }
];
const addresses = [
  '0xc987eb2E50959b51e74056Ee62c8F0e437c3a56f',
];

(async () => {
  console.time('getScores');
  try {
    const scores = await snapshot.utils.getScores(
      space,
      strategies,
      network,
      new JsonRpcProvider(networks[network].rpc[0]),
      addresses,
      'latest'
    );
    console.log(scores);
  } catch (e) {
    console.log('getScores failed');
    console.error(e);
  }
  console.timeEnd('getScores');
})();
```

The address in the addresses array has had ~277 INDEX delegated to it from `0xf6401adc23Faa6B9AD83eA8604CA7254CB7F53e7`, yet this code results in a score of 0 index. If I remove the sushiswap strategy from the delegation that it correctly displays 277 index as my voting power.

**Review by ChaituVR — APPROVED** [review]
LGTM @bonustrack

**Review by bonustrack — APPROVED** [review]
Works well thank you for the fix @ncitron !

**Pull request merged**
