### PR TITLE
DefiDollar Strategy

### PR DESCRIPTION
**Pull request by atvanguard**
Changes proposed in this pull request:
- Adds token balances across [DefiDollar](http://dusd.finance/) farming pools.

### CODE REVIEW

**Review by bonustrack — COMMENTED** [review]
Looks good! Can you just remove changes on the test/index.ts file and run the script 'lint' `npm run lint`?

**Comment by atvanguard** [comment]
@bonustrack Thanks! Pushed both the changes.

**Comment by bonustrack** [comment]
@atvanguard Can you fix the conflict?

**Comment by atvanguard** [comment]
@bonustrack Done!

**Pull request merged**
