### PR TITLE
Optimistic Ethereum Network

### PR DESCRIPTION
**Pull request by ChaituVR**
https://chainid.link/?network=optimism

### CODE REVIEW

**Comment by ChaituVR** [comment]
Blocked by https://github.com/snapshot-labs/snapshot/issues/634

**Comment by elenadimitrova** [comment]
This also needs a logo in /src/networks 
You can use https://github.com/ethereum-optimism/brand-kit/blob/main/assets/images/Profile-Logo.png

**Comment by bonustrack** [comment]
Good point thanks @elenadimitrova !
^@ChaituVR

**Comment by ChaituVR** [comment]
Thanks, @elenadimitrova :) Added image @bonustrack

**Review by bonustrack — APPROVED** [review]

**Comment by elenadimitrova** [comment]
@ChaituVR @bonustrack Is there anything else required to bring Optimism to the Front end here https://snapshot.org/#/?network=10

**Comment by ChaituVR** [comment]
@elenadimitrova It is already live on snapshot https://snapshot.org/#/networks?q=optimistic Feel free to give us some early feedback if something doesn't work with this network :)

**Pull request merged**
