### PR TITLE
feat: supporting custom networks file

### PR DESCRIPTION
**Pull request by CjHare**
An implementation for the code side for https://github.com/snapshot-labs/snapshot.js/issues/381

Figured there may be changes wanted around precisely how or which methods of input are to be supported, or where that logic resides, so I've held off on updating the README. (When that's set, then I'll add the update to the docs).

Reviews are welcome 🙂

### CODE REVIEW

**Comment by ChaituVR** [comment]
Nice Idea @CjHare

**Review by bonustrack — COMMENTED** [review]
Files in src/ shouldn't include process.env or others env specific variables. Can't you just do like this to add a new network:

```ts
import networks from '@snapshot-labs/snapshot.js/src/networks.json';

networks[12345] = {
  id: '12345',
  name: 'Custom node',
  rpc: ['http://localhost:88383']
  multicall: '0x123456'
};
```

**Comment by ChaituVR** [comment]
@bonustrack This one is actually for `snapshot-strategies` networks come from `snapshot.cjs` and won't be able to change them without modifying `node_modules` folder

**Comment by CjHare** [comment]
> Files in src/ shouldn't include process.env or others env specific variables.
That does make sense. 

As @ChaituVR points out these changes avoids some code duplication in a `snapshot-strategies` PR by allowing the networks to be from an alternative source to the `networks.json` (in this case using a local file instead). 
What would be the recommendation to achieve that change within the Snapshot packages/project structure?

**Comment by bonustrack** [comment]
@CjHare Sorry for late review, this PR is not relevant for this repository, the change should be on https://github.com/snapshot-labs/snapshot-strategies , I would suggest make custom network an option in getScoreDirect function instead of using npm vars or config vars.

**Pull request closed without merging**
