### PR TITLE
Lint on commit

### PR DESCRIPTION
**Pull request by ChaituVR**

### CODE REVIEW

**Comment by ChaituVR** [comment]
[Add lint test in Snapshot.js](https://trello.com/c/2cRVtVl1/177-add-lint-test-in-snapshotjs)

**Review by rude69 — APPROVED** [review]

**Review by rude69 — COMMENTED** [review]
testing good

**Review by rude69 — APPROVED** [review]

**Review by rude69 — APPROVED** [review]

**Review by rude69 — APPROVED** [review]
[Node CI](https://github.com/snapshot-labs/snapshot.js/actions/workflows/nodejs.yml)

**Review by rude69 — APPROVED** [review]

**Comment by rude69** [comment]
[Node CI](https://github.com/snapshot-labs/snapshot.js/actions/workflows/nodejs.yml)

**Pull request closed without merging**
