### PR TITLE
Add a full sync node for Heco chain

### PR DESCRIPTION
**Pull request by dogeswapfans**
Fixes # .

Changes proposed in this pull request:
- Current rpc node isn't a full sync node, which will cause ""missing trie node" issue, try this new added node provided by Heco community.

### CODE REVIEW

**Comment by dogeswapfans** [comment]
Not sure is it necessary to delete previous node which isn't a full sync node.

**Review by bonustrack — APPROVED** [review]
Let's try

**Comment by dogeswapfans** [comment]
@bonustrack Does it need to update the release of npm package?

**Comment by bonustrack** [comment]
@dogeswapfans No, it should be live already, does it work for you? You may need to clear your cache

**Comment by dogeswapfans** [comment]
Unfortunately, it seems this is still not a full sync node, same error output on the console

**Comment by bonustrack** [comment]
I recommend get in touch with the officials, they might be able to help.

**Comment by dogeswapfans** [comment]
Yes, we asked, they ask projects to build own full sync node, which is unfriendly to community projects like your team

**Pull request merged**
