### PR TITLE
Fix the format of the returned score values

### PR DESCRIPTION
**Pull request by w1kke**
Fixes # .

Changes proposed in this pull request:
- The voting works correctly with the last version of the strategy
- But the display of the voting power is not correct
- This has been corrected from my understanding but now it has to be proven in a test vote

### CODE REVIEW

**Comment by bonustrack** [comment]
@w1kke Can you resolve the conflicts?

**Comment by w1kke** [comment]
@bonustrack I resolved them

**Review by bonustrack — APPROVED** [review]
Looks good! Thanks and sorry for the delay

**Comment by bonustrack** [comment]
The change on the strategy is live.

**Pull request merged**
