### PR TITLE
Add Hoo Smart Chain Support

### PR DESCRIPTION
**Pull request by vvvictorlee**
Fixes # .

Changes proposed in this pull request:
- 
- 
-

### CODE REVIEW

**Comment by vvvictorlee** [comment]
@bonustrack @ChaituVR

**Comment by ChaituVR** [comment]
LGTM

**Comment by bonustrack** [comment]
@vvvictorlee Looks good! Can you just add an image on this folder: https://github.com/snapshot-labs/snapshot.js/tree/master/src/networks

**Comment by vvvictorlee** [comment]
> @vvvictorlee Looks good! Can you just add an image on this folder: https://github.com/snapshot-labs/snapshot.js/tree/master/src/networks

I  haved added it.  @bonustrack

**Review by bonustrack — APPROVED** [review]
Looks good!

**Pull request merged**
