### PR TITLE
Adding RSK Mainnet and Testnet networks

### PR DESCRIPTION
**Pull request by aeidelman**
Changes proposed in this pull request:
- Add RSK Mainnet Network (id: 30)
- Add RSK Testnet Network (id: 31)

### CODE REVIEW

**Review by ChaituVR — COMMENTED** [review]
LGTM @bonustrack

**Comment by bonustrack** [comment]
Hi @aeidelman! Thanks for your contribution, you will need to add a multicall contract to make it work, have a look here for more info: https://docs.snapshot.org/networks

**Comment by aeidelman** [comment]
Hi @bonustrack, I've added it as a separate PR (#182). Please let me know if that's ok. Thanks!

**Review by bonustrack — APPROVED** [review]

**Comment by bonustrack** [comment]
@aeidelman Ho yes, my bad i've missed the other PR. The changes are deployed now https://snapshot.org/#/networks?q=rsk

**Comment by aeidelman** [comment]
@bonustrack that was fast! We'll be trying snapshot in RSK, thanks!

**Comment by bonustrack** [comment]
Awesome! Come to our Discord if you need help.

**Pull request merged**
