### PR TITLE
Added findora network

### PR DESCRIPTION
**Pull request by ws4charlie**
Changes proposed in this pull request:

1. Added Findora mainnet
2. The previous PR: https://github.com/snapshot-labs/snapshot.js/pull/769

### CODE REVIEW

**Comment by ws4charlie** [comment]
The context: 
image

image

@ChaituVR I didn't get what you mean by "Also the node has a very less node limit, make sure it has good limit". What LIMIT you meant and what we need to do to increase that limit?

**Comment by ChaituVR** [comment]
@ws4charlie I mean try passing a big payload or test your network/node as mentioned here https://docs.snapshot.org/guides/networks#add-a-new-network

**Comment by ws4charlie** [comment]
> @ws4charlie I mean try passing a big payload or test your network/node as mentioned here https://docs.snapshot.org/guides/networks#add-a-new-network

Thanks for your response @ChaituVR . Our devops says that the payload size limit on our endpoint (the archive node) is 100Mb and I believe that should be big enough. Also, I tested our endpoint according to this link and get below result. https://docs.snapshot.org/guides/networks#add-a-new-network
image

Can you please provide a test command (e.g., a curl command or some steps) so our team can perform the test against the endpoint and replicate your error? Thank you very much.

**Comment by ChaituVR** [comment]
@ws4charlie In the screenshot you provided, should wait until the last column shows a number, it should be a minimum of 500

**Comment by ws4charlie** [comment]
@ChaituVR Could you please tell us the meaning of the number in column `NODE LIMIT (MAX 10000 ADDRESSES)`? It's hard to know what adjustments should be made to the node without knowing what tests are being perform in the back scene for that column. Was that a `MULTICALL` test or getBalance() test? I would appreciate if you could provide a bit explanation.
image

**Comment by ChaituVR** [comment]
Hi @ws4charlie So it is just the number of addresses passed into a the multicall to get the balance of these addresses

**Comment by ws4charlie** [comment]
> addresses
Thanks @ChaituVR. Also, please also confirm the call your test made was invoking below `aggregate` method?
image

**Comment by ChaituVR** [comment]
Closing this as stale, feel free to reopen if needed

**Pull request closed without merging**
