### PR TITLE
support custom score api url as function param (and removed unused provider param)

### PR DESCRIPTION
**Pull request by mktcode**
fixes: https://github.com/snapshot-labs/snapshot.js/issues/402

Needs adjustments in [more places](https://github.com/search?p=1&q=org%3Asnapshot-labs+getScores&type=Code) once snapshot.js version gets bumped up.

### CODE REVIEW

**Comment by ChaituVR** [comment]
@mktcode This looks good to me, ready to merge this, but the build is failing in GitHub actions with the below error:

```js
src/index.ts → dist/snapshot.min.js...
[!] (plugin rpt2) Error: /home/runner/work/snapshot.js/snapshot.js/src/validations/basic/index.ts(19,26): semantic error TS2554: Expected 6 arguments, but got 4.
src/validations/basic/index.ts
Error: /home/runner/work/snapshot.js/snapshot.js/src/validations/basic/index.ts(19,26): semantic error TS2554: Expected 6 arguments, but got 4.
    at error (/home/runner/work/snapshot.js/snapshot.js/node_modules/rollup/dist/shared/rollup.js:5265:30)
    at throwPluginError (/home/runner/work/snapshot.js/snapshot.js/node_modules/rollup/dist/shared/rollup.js:17956:12)
    at Object.error (/home/runner/work/snapshot.js/snapshot.js/node_modules/rollup/dist/shared/rollup.js:18563:24)
    at Object.error (/home/runner/work/snapshot.js/snapshot.js/node_modules/rollup/dist/shared/rollup.js:18125:38)
    at RollupContext.error (/home/runner/work/snapshot.js/snapshot.js/node_modules/rollup-plugin-typescript2/src/rollupcontext.ts:37:18)
    at lodash_3 (/home/runner/work/snapshot.js/snapshot.js/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:41:11)
    at arrayEach (/home/runner/work/snapshot.js/snapshot.js/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:516:11)
    at _.each (/home/runner/work/snapshot.js/snapshot.js/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:9342:14)
    at printDiagnostics (/home/runner/work/snapshot.js/snapshot.js/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:9:2)
    at Object.transform (/home/runner/work/snapshot.js/snapshot.js/node_modules/rollup-plugin-typescript2/src/index.ts:242:5)
```

**Comment by mktcode** [comment]
Yeah I saw that... didn't take a closer look yet. Will do today.

**Comment by mktcode** [comment]
> @mktcode This looks good to me, ready to merge this, but the build is failing in GitHub actions with the below error:

Resolved. I'm not so familiar with TypeScript and the syntax for setting the function param's default values was wrong.

**Review by ChaituVR — APPROVED** [review]
LGTM 👍

**Review by bonustrack — APPROVED** [review]

**Pull request merged**
